    name: 'My JavaScript Action'
    description: 'A simple action to demonstrate JavaScript execution.'
    inputs:
      who-to-greet:
        description: 'Who to greet in the log'
        required: true
        default: 'World'
    outputs:
      time:
        description: 'The time of greeting'
    runs:
      using: 'node20' # Or a compatible Node.js version like 'node16', 'node18'
      main: 'index.js' # The main JavaScript file to execute

