name: Run JS File

on:
  workflow_dispatch:  # allows manual triggering

jobs:
  run-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run JS using Node
        run: node script.js


