name: GitHub OIDC Token Example

on:
  workflow_dispatch:

jobs:
  get-oidc-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC!
      contents: read

    steps:
      - name: Request OIDC token
        id: oidc
        run: |
          echo "Requesting OIDC token..."
          TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                      "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://vault.example.com" | jq -r '.value')

          echo "::add-mask::$TOKEN"
          echo "OIDC token acquired successfully."

      - name: Done
        run: echo "OIDC setup test complete."

