name: Basic Action

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello message
        run: echo "Hello from GH actions"

      - name: Show github context
        run:  echo "Repository $GITHUB_REPOSITORY, actor: $GITHUB_ACTOR"

