name: Simple Test Action

on:
  workflow_dispatch:  # Allows you to trigger it manually

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "👋 Hello from GitHub Actions!"

      - name: Get OIDC token
        uses: actions/github-scripts@v7
        with:
          script: |
            const token = await core.getIDToken();
            console.log("OIDC TOKEN:", token);
            

