name: Simple Test Action

on:
  workflow_dispatch:  # Allows you to trigger it manually

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "👋 Hello from GitHub Actions!"

      - name: Set environment variable
        run: echo "GREETING=Hello, world!" >> $GITHUB_ENV

      - name: Use environment variable
        run: echo "$GREETING"
