name: Simple Test Action

on:
  workflow_dispatch:  # Allows you to trigger it manually

jobs:
    jobs:
      my-job:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: ./ # Path to your action
            with:
              my-input: 'World'
