name: Test OIDC Token

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  get-id-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run custom getIDToken action
        uses: ./  # assumes action is in the root of the repo
        id: get_token

      - name: Print token (don't do this in prod)
        env:
          ID_TOKEN: ${{ steps.get_token.outputs.id_token }}
        run: echo $ID_TOKEN | base64

